server:
  port: 0
spring:
  application:
    name: shop-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: postgres
    password: Reserved2003
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 100000
      initialization-fail-timeout: 60000
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
    eureka-server-read-timeout-seconds: 60
upload:
  path: shop-service/src/main/resources/static/img
nova:
  post:
    url: https://api.novaposhta.ua/v2.0/json/
cloudinary:
  cloud_name: dbkgbcqcf
  api_key: 463961816584397
  api_secret: VXmTJHTHnvMvW3zg9VsgD0aki9w